# Generated by Django 4.2.7 on 2023-12-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_trainingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAlignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SAMPLE_NUM', models.CharField(max_length=255)),
                ('SAMPLE_NUM_SUCCESS', models.CharField(max_length=255)),
            ],
        ),
    ]
