# Generated by Django 4.2.7 on 2023-12-21 07:03
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_trainingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAlignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SAMPLE_NUM', models.CharField(max_length=255)),
                ('SAMPLE_NUM_SUCCESS', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('account', models.CharField(max_length=255, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('com', models.CharField(max_length=255, verbose_name='所属公司')),
                ('comid', models.IntegerField(default=0, verbose_name='公司ID')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理后台权限')),
                ('groups', models.ManyToManyField(blank=True,
                                                  help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                                  related_name='user_set', related_query_name='user', to='auth.group',
                                                  verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                                                            related_name='user_set', related_query_name='user',
                                                            to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'login_user',
            },
        ),
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('assetID', models.AutoField(primary_key=True, serialize=False)),
                ('assetName', models.CharField(max_length=100, verbose_name='名称')),
                ('assetOwner', models.CharField(max_length=100, verbose_name='所有者')),
                ('description', models.TextField(verbose_name='描述')),
                ('assetFormat', models.CharField(max_length=50, verbose_name='格式')),
                ('assetLevel',
                 models.CharField(choices=[('L1', '高敏感密文'), ('L2', '高敏感'), ('L3', '敏感'), ('L4', '低敏感')],
                                  max_length=10, verbose_name='安全等级')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('assetPath', models.CharField(default='无', max_length=200, verbose_name='访问路径')),
            ],
            options={
                'verbose_name': '数据资产',
                'verbose_name_plural': '数据资产',
            },
        ),
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=255, verbose_name='资产名称')),
                ('assetOwner', models.CharField(max_length=255, verbose_name='资产所有者')),
                ('assetFormat', models.CharField(max_length=100, verbose_name='资产格式')),
                ('assetLevel', models.CharField(max_length=100, verbose_name='资产级别')),
                ('assetPath', models.CharField(max_length=255, verbose_name='资产路径')),
                ('star_status', models.CharField(default='默认值', max_length=50, verbose_name='开始状态')),
                ('end_status', models.CharField(default='默认值', max_length=50, verbose_name='结束状态')),
                ('operation', models.CharField(default='默认值', max_length=50, verbose_name='操作')),
                ('txTime', models.DateTimeField(blank=True, null=True, verbose_name='交易时间')),
                ('txID', models.CharField(blank=True, max_length=255, null=True, verbose_name='交易ID')),
                ('txHash', models.CharField(blank=True, max_length=255, null=True, verbose_name='交易哈希')),
            ],
            options={
                'verbose_name': '资产记录',
                'verbose_name_plural': '资产记录',
                'db_table': 'asset_record',
            },
        ),
    ]
