# Generated by Django 5.2 on 2025-04-28 14:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=255, verbose_name='资产名称')),
                ('assetOwner', models.CharField(max_length=255, verbose_name='资产所有者')),
                ('assetFormat', models.CharField(max_length=100, verbose_name='资产格式')),
                ('assetLevel', models.CharField(max_length=100, verbose_name='资产级别')),
                ('assetPath', models.CharField(max_length=255, verbose_name='资产路径')),
                ('star_status', models.CharField(default='默认值', max_length=50, verbose_name='开始状态')),
                ('end_status', models.CharField(default='默认值', max_length=50, verbose_name='结束状态')),
                ('operation', models.CharField(default='默认值', max_length=50, verbose_name='操作')),
                ('txTime', models.DateTimeField(blank=True, null=True, verbose_name='交易时间')),
                ('txID', models.CharField(blank=True, max_length=255, null=True, verbose_name='交易ID')),
                ('txHash', models.CharField(blank=True, max_length=255, null=True, verbose_name='交易哈希')),
            ],
            options={
                'verbose_name': '资产记录',
                'verbose_name_plural': '资产记录',
                'db_table': 'asset_record',
            },
        ),
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('assetID', models.AutoField(primary_key=True, serialize=False)),
                ('assetName', models.CharField(max_length=100, verbose_name='名称')),
                ('assetOwner', models.CharField(max_length=100, verbose_name='所有者')),
                ('description', models.TextField(verbose_name='描述')),
                ('assetFormat', models.CharField(max_length=50, verbose_name='格式')),
                ('assetLevel', models.CharField(choices=[('L1', '高敏感密文'), ('L2', '高敏感'), ('L3', '敏感'), ('L4', '低敏感')], max_length=10, verbose_name='安全等级')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('assetPath', models.CharField(default='无', max_length=200, verbose_name='访问路径')),
            ],
            options={
                'verbose_name': '数据资产',
                'verbose_name_plural': '数据资产',
            },
        ),
        migrations.CreateModel(
            name='DataAsset1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资产名称')),
                ('asset_type', models.CharField(choices=[('铁路准入到货信息', '铁路准入到货信息'), ('预配舱单', '预配舱单'), ('理货报告编制要求', '理货报告编制要求')], max_length=50, verbose_name='资产类型')),
                ('owner', models.CharField(choices=[('customs', '海关'), ('port', '港口'), ('railway', '铁路'), ('foreign', '外方')], max_length=20, verbose_name='所有方')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('file_path', models.CharField(max_length=255, verbose_name='文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据资产',
                'verbose_name_plural': '数据资产',
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('account', models.CharField(max_length=255, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('com', models.CharField(max_length=255, verbose_name='所属公司')),
                ('comid', models.IntegerField(default=0, verbose_name='公司ID')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理后台权限')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'login_user',
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_reason', models.TextField(verbose_name='申请原因')),
                ('request_purpose', models.TextField(verbose_name='用途说明')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='申请状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dataasset1', verbose_name='申请资产')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '数据申请',
                'verbose_name_plural': '数据申请',
            },
        ),
        migrations.CreateModel(
            name='DataAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='授权时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='授权备注')),
                ('authorizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='授权人')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.datarequest', verbose_name='关联申请')),
            ],
            options={
                'verbose_name': '数据授权',
                'verbose_name_plural': '数据授权',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('request', '申请数据'), ('approve', '批准申请'), ('reject', '拒绝申请'), ('view', '查看数据')], max_length=20, verbose_name='操作类型')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operation_detail', models.TextField(verbose_name='操作详情')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.datarequest', verbose_name='关联申请')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
            },
        ),
    ]
